---
title: Randy Lubin's Personal Blog
timezone: UTC
collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
email: randylubin@gmail.com
description: Randy Lubin's personal blog. Contains writing on travel, startups, technology,
  games, and more.
baseurl: "/"
url: https://blog.randylubin.com
twitter_username: randylubin
github_username: randylubin
permalink: "/:slug"
plugins:
- jekyll-feed
sass:
  sass_dir: _sass
